#!/bin/bash
# NeoForge server launcher


export MAIN_DIR=$PWD
export JAVA=$MAIN_DIR/bin/java_bins/bin/java
cd server


# Detect system memory in GB
total_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mem_gb=$(($total_kb/1024/1024))


# NeoForge uses a generated run script, but when launching manually we still run the main server jar.
# The server jar for NeoForge is usually named: neoforge-<version>-server.jar
# Make sure the filename below matches your installed version.


JAR_NAME=$(ls neoforge*-server.jar 2>/dev/null | head -n 1)


if [ -z "$JAR_NAME" ]; then
echo "❌ 找不到 NeoForge server jar，請確認檔案名稱 neoforge-*-server.jar 是否存在於 server/ 內"
exit 1
fi


# Start NeoForge server
$JAVA -Xmx${mem_gb}G -Xms${mem_gb}G -jar "$JAR_NAME" nogui
